-- ROLE
INSERT INTO TB_ROLE(`ROLE_NAME`) VALUES('ROLE_ADMIN');
INSERT INTO TB_ROLE(`ROLE_NAME`) VALUES('ROLE_MANAGER');
INSERT INTO TB_ROLE(`ROLE_NAME`) VALUES('ROLE_USER');

SELECT * FROM TB_ROLE ORDER BY 1;